baseURL: 'https://amaro.pages.dev/'
languageCode: en-us
title: Amaro 101
theme: PaperMod
params:
    defaultTheme: dark 

    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    homeInfoParams:
              Title: Welcome to Amaro 101  
              Content: "The goal of this site is to create a brief introduction to amaro for servers, bartenders, and other service industry personnel.          This site should function as a short, 10 minute reference guide for new employees or as a quick reminder for experienced ones to help industry employees gain and maintain a solid foundation of knowledge for selling amaro to guests with confidence."
              

menu:
    main:
         -  identifier: About
            name: About
            url: /posts/what_is_amaro/
            weight: 10
         -  identifier: Ingredients
            name: Ingredients
            url: /posts/ingredients/
            weight: 20
         -  identifier: Types
            name: Types
            url: /posts/types/
            weight: 30

