baseURL: 'https://amaro.pages.dev/'
languageCode: en-us
title: Amaro 101
theme: PaperMod
params:
    defaultTheme: dark 
    socialIcons: 
         -  name: "github"
            url: "https://github.com/caciulla"
         -  name: "twitter"
            url: "https://twitter.com/ChaceCiulla"
        # - name: "gmail"
        #     url: 
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    homeInfoParams:
              Title: Welcome to Amaro 101  👋
              Content: "Hello, the goal of this site is to offer employees of the service industry a brief introduction—or quick refresher—on the world of amaro. This is not meant to be a comprehensive guide. It is my hope to create something that can serve as a quick, ten-minute crash course that will help anyone in the service industry, learn about, talk about, and sell amaro with confidence. Cheers 🥃"
              

menu:
    main:
         -  identifier: About
            name: About
            url: /posts/what_is_amaro/
            weight: 10
         -  identifier: Ingredients
            name: Ingredients
            url: /posts/ingredients/
            weight: 20
         -  identifier: Types
            name: Types
            url: /posts/types/
            weight: 30

