baseURL: 'https://amaro.pages.dev/'
languageCode: en-us
title: Amaro 101
theme: PaperMod
params:
    defaultTheme: dark 
    socialIcons: 
         -  name: "github"
            url: "https://github.com/caciulla"
         -  name: "twitter"
            url: "https://twitter.com/ChaceCiulla"
        # - name: "gmail"
        #     url: 
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    homeInfoParams:
              Title: Welcome to Amaro 101  👋
              Content: "This is a ten minute crash course on amaro. If you're a server or bartender and you're new to amaro, this site will give you the information you need to talk about and sell amaro with confidence. Cheers 🥃"
              

menu:
    main:
         -  identifier: About
            name: About
            url: /posts/what_is_amaro/
            weight: 10
         -  identifier: Ingredients
            name: Ingredients
            url: /posts/ingredients/
            weight: 20
         -  identifier: Types
            name: Types
            url: /posts/types/
            weight: 30

